#pragma once

#define MIDI_BASIC

#define DYNAMIC_KEYMAP_LAYER_COUNT 8

#ifdef RGB_DI_PIN
#    undef RGBLIGHT_HUE_STEP
#    undef RGBLIGHT_SAT_STEP
#    undef RGBLIGHT_VAL_STEP
#    undef RGBLIGHT_ANIMATIONS
#    undef RGBLIGHT_BREATHE_TABLE_SIZE
#    undef RGBLIGHT_EFFECT_BREATHE_CENTER
#    undef RGBLIGHT_EFFECT_BREATHE_MAX
#    undef RGBLIGHT_DEFAULT_MODE
#    define RGBLIGHT_LAYERS_OVERRIDE_RGB_OFF
#    define RGBLIGHT_DEFAULT_MODE 0
#    define RGBLIGHT_LED_MAP { 6, 5, 4, 3, 2, 1, 0 }
#endif
