VIA_ENABLE = yes
VIAL_ENABLE = yes
VIAL_INSECURE = yes
# firmware reducing
KEY_OVERRIDE_ENABLE = yes
COMBO_ENABLE = yes
TAP_DANCE_ENABLE = yes
VIALRGB_ENABLE = yes

RGB_MATRIX_CUSTOM_KB = yes
ENCODER_MAP_ENABLE = yes
